---
- hosts: all
  gather_facts: no
  tasks:
    - name: Running apt update
      apt: update_cache=yes
    - name: Installing required packages
      apt: name={{item}} state=present
      with_items:
       - fail2ban
       - postgresql
       - postgresql-client
       - git
       -  python3-pip #updated
       - rdiff-backup
       - libpq-dev
       - python3-psycopg2   #cross fingers digitally    
#       - python-psycopg2-doc #updated
#       - python-psycopg2
       - uwsgi 
       - uwsgi-plugin-python3  # Use uwsgi-plugin-python3 instead of uwsgi-plugin-python
#       - uwsgi-plugin-python
       - nginx
